apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o pathfinder-rpc-server --volumes persistentVolumeClaim -c -f docker-compose.pathfinder-pull.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: blockchain-indexer
  name: blockchain-indexer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: blockchain-indexer
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o pathfinder-rpc-server --volumes persistentVolumeClaim -c -f docker-compose.pathfinder-pull.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: blockchain-indexer
    spec:
      containers:
        - env:
            - name: HUB_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: HUB_ADDRESS
                  name: env
            - name: INDEXER_CONNECTION_STRING
              valueFrom: 
                configMapKeyRef:
                  key: INDEXER_CONNECTION_STRING
                  name: env 
            - name: INDEXER_RPC_GATEWAY_URL
              valueFrom:
                configMapKeyRef:
                  key: INDEXER_RPC_GATEWAY_URL
                  name: env
            - name: INDEXER_WEBSOCKET_URL
              valueFrom:
                configMapKeyRef:
                  key: INDEXER_WEBSOCKET_URL
                  name: env
          image: circlesubi/blockchain-indexer:latest
          name: blockchain-indexer
          ports:
            - containerPort: 8675
          resources: {}
      restartPolicy: Always
status: {}
