{{- if .Values.blockchainIndexer.enabled -}}
apiVersion: v1
kind: Service
metadata:    
  labels:
    app: blockchain-indexer
  name: blockchain-indexer
spec:
  ports:
    - name: ws 
      port: 8675
      targetPort: 8675
  selector:
    app: blockchain-indexer
{{- end -}}
