apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: blockchain-indexer
  name: blockchain-indexer
  namespace: pathfinder
spec:
  clusterIP: None
  ports:
    - name: "8675"
      port: 8675
      targetPort: 8675
  selector:
    io.kompose.service: blockchain-indexer
  type: ClusterIP
status:
  loadBalancer: {}
