{{- if index .Values "blockchain-indexer" "enabled" -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: blockchain-indexer
  name: blockchain-indexer
  namespace: pathfinder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockchain-indexer
  serviceName: blockchain-indexer
  template:
    metadata:
      labels:
        app: blockchain-indexer
    spec:
      containers:
        - env:
          - name:     HUB_ADDRESS
            valueFrom:
              configMapKeyRef:
                key:  HUB_ADDRESS
                name: pathfinder-environment
          - name:     INDEXER_CONNECTION_STRING
            valueFrom: 
              secretKeyRef:
                key:  BLOCKCHAIN_INDEXER_CONNECTION_STRING
                name: blockchain-indexer-connection-string 
          - name:     INDEXER_RPC_GATEWAY_URL
            valueFrom:
              configMapKeyRef:
                key:  INDEXER_RPC_GATEWAY_URL
                name: pathfinder-environment
          - name:     INDEXER_WEBSOCKET_URL
            valueFrom:
              configMapKeyRef:
                key:  INDEXER_WEBSOCKET_URL
                name: pathfinder-environment
          - name:     START_FROM_BLOCK
            valueFrom:
              configMapKeyRef:
                key:  START_FROM_BLOCK 
                name: env 
          image: circlesubi/blockchain-indexer:latest
          name: blockchain-indexer
          ports:
            - containerPort: 8675
          resources: {}
      restartPolicy: Always
  updateStrategy: {}
{{- end -}}
