apiVersion: v1
kind: ConfigMap
metadata:
  name: env
data:
  # Blockchain Indexer   
  # ~~~~~~~~~~~~~~~~~~~~~~
  HUB_ADDRESS: {{.Values.contracts.hubAddress}}
  INDEXER_CONNECTION_STRING: {{.Values.blockchainIndexer.indexerConnectionString }}
  INDEXER_RPC_GATEWAY_URL: {{ .Values.blockchainIndexer.indexerRPCGatewayURL }}
  INDEXER_WEBSOCKET_URL: {{ .Values.blockchainIndexer.indexerWebsocketURL }}

  # Indexer DB
  # secret BLOCKCHAIN_INDEXER_POSTGRES_PASSWORD: {{ .Values. }}
  BLOCKCHAIN_INDEXER_POSTGRES_DB: {{ .Values.indexerDB.db }}
  BLOCKCHAIN_INDEXER_POSTGRES_USER: {{ .Values.indexerDB.user }}
  BLOCKCHAIN_INDEXER_POSTGRES_PGDATA: {{ .Values.indexerDB.pgdata }}

  # Pathfinder proxy

  PATHFINDER_PROXY_PORT: {{ .Values.pathfinderProxy.port }}
  PATHFINDER_PROXY_CORS_ORIGINS: {{ .Values.pathfinderProxy.corsOrigins }}
  PATHFINDER_PROXY_UPSTREAM_SERVICE_ENDPOINTS: {{ .Values.pathfinderProxy.upstreamServiceEndpoints }}
  PATHFINDER_PROXY_UPSTREAM_HEALTH_ENDPOINTS:   {{ .Values.pathfinderProxy.upstreamHealthEndpoints }}     

  # Pathfinder updater 

PATHFINDER_UPDATER_INDEXER_DB_CONNECTION_STRING: {{ .Values.pathfinderUpdater.indexerDBConnectionString }}
PATHFINDER_UPDATER_INDEXER_WS_URL: {{ .Values.pathfinderUpdater.indexerWSurl }}
PATHFINDER_UPDATER_INTERNAL_CAPACITY_GRAPH_PATH: {{ .Values.pathfinderUpdater.internalCapacityGraph }}
PATHFINDER_UPDATER_EXTERNAL_CAPACITY_GRAPH_PATH: {{ .Values.pathfinderUpdater.externalCapacityGraph }}
PATHFINDER_UPDATER_RPC_URL: {{ .Values.pathfinderUpdater.rpcURL }}