apiVersion: v1
kind: ConfigMap
metadata:
  name: pathfinder-environment
data:
  {{- if .Values.blockchainIndexer.enabled }}
  HUB_ADDRESS:                                    {{ .Values.blockchainIndexer.hubAddress }}
  INDEXER_RPC_GATEWAY_URL:                        {{ .Values.blockchainIndexer.indexerRPCGatewayURL }}
  INDEXER_WEBSOCKET_URL:                          {{ .Values.blockchainIndexer.indexerWebsocketURL }}
  START_FROM_BLOCK:                               '{{ .Values.blockchainIndexer.startFromBlock }}'
  {{- end }}

  {{- if .Values.pathfinderProxy.enabled }}
  PATHFINDER_PROXY_PORT:                           {{ .Values.pathfinderProxy.port }}
  PATHFINDER_PROXY_CORS_ORIGINS:                   {{ .Values.pathfinderProxy.corsOrigins }}
  PATHFINDER_PROXY_UPSTREAM_SERVICE_ENDPOINTS:     {{ .Values.pathfinderProxy.upstream.serviceEndpoints }}
  PATHFINDER_PROXY_UPSTREAM_HEALTH_ENDPOINTS:      {{ .Values.pathfinderProxy.upstream.healthEndpoints }}
  {{- end }}

  {{- if  .Values.pathfinder.enabled }}
  PATHFINDER_UPDATER_INDEXER_WS_URL:                {{ .Values.pathfinder.indexerWSurl }}
  PATHFINDER_UPDATER_INTERNAL_CAPACITY_GRAPH_PATH:  {{ .Values.pathfinder.internalCapacityGraph }}
  PATHFINDER_UPDATER_EXTERNAL_CAPACITY_GRAPH_PATH:  {{ .Values.pathfinder.externalCapacityGraph }}
  PATHFINDER_UPDATER_RPC_URL:                       {{ .Values.pathfinder.rpcURL }}
  {{- end }}
