apiVersion: v1
kind: ConfigMap
metadata:
  name: pathfinder-environment
  namespace: pathfinder
data:
  {{- if index .Values "blockchain-indexer" "enabled" }}
  HUB_ADDRESS:                                    {{ index .Values "blockchain-indexer" "hub-address" }}
  INDEXER_RPC_GATEWAY_URL:                        {{ index .Values "blockchain-indexer" "indexer-rpc-gateway-url" }}
  INDEXER_WEBSOCKET_URL:                          {{ index .Values "blockchain-indexer" "indexer-websocket-url" }}
  START_FROM_BLOCK:                              '{{ index .Values "blockchain-indexer" "start-from-block" }}'
  {{- end }}
  {{- if index .Values "pathfinder-proxy" "enabled" }}
  PATHFINDER_PROXY_PORT:                          '{{ index .Values "pathfinder-proxy" "port" }}'
  PATHFINDER_PROXY_CORS_ORIGINS:                   {{ index .Values "pathfinder-proxy" "cors-origins" }}
  PATHFINDER_PROXY_UPSTREAM_SERVICE_ENDPOINTS:     {{ index .Values "pathfinder-proxy" "upstream" "service-endpoints" }}
  PATHFINDER_PROXY_UPSTREAM_HEALTH_ENDPOINTS:      {{ index .Values "pathfinder-proxy" "upstream" "health-endpoints" }}
  {{- end }}
  {{- if .Values.pathfinder.enabled }}
  PATHFINDER_UPDATER_INDEXER_WS_URL:               {{ index .Values.pathfinder "indexer-ws-url" }}
  PATHFINDER_UPDATER_INTERNAL_CAPACITY_GRAPH_PATH: {{ index .Values.pathfinder "internal-capacity-graph" }}
  PATHFINDER_UPDATER_EXTERNAL_CAPACITY_GRAPH_PATH: {{ index .Values.pathfinder "external-capacity-graph" }}
  PATHFINDER_UPDATER_RPC_URL:                      {{ index .Values.pathfinder "rpc-url" }}
  {{- end }}
