apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cors-headers
  namespace: pathfinder
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "PUT"
      - "POST"
    accessControlAllowHeaders:
      - "*"
    accessControlAllowOriginList: {{ toYaml .Values.CORS_allowed | nindent 6 }}
    accessControlAllowOriginListRegex: {{ toYaml .Values.CORS_allowed_regex | nindent 6 }} 
    accessControlMaxAge: 100
    addVaryHeader: true
