{{- if .Values.ingress.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: pathfinder-corsheaders
  namespace: pathfinder
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "PUT"
      - "POST"
    accessControlAllowHeaders:
      - "*"
    accessControlAllowOriginList: {{ index .Values "pathfinder-proxy" "cors-origins" "list" }}
    accessControlAllowOriginListRegex: {{ index .Values "pathfinder-proxy" "cors-origins" "listregex" }}
    accessControlMaxAge: 100
    addVaryHeader: true
{{- end -}}
