{{- if .Values.ingress.middlewares.cors.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.ingress.middlewares.cors.name }}
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "PUT"
      - "POST"
    accessControlAllowHeaders:
      - "*"
    {{- with index .Values.ingress.middlewares.cors.origins "list" }}
    accessControlAllowOriginList:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with index .Values.ingress.middlewares.cors.origins "listRegex" }}
    accessControlAllowOriginListRegex:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    accessControlMaxAge: 100
    addVaryHeader: true
{{- end -}}
