apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o pathfinder-rpc-server --volumes persistentVolumeClaim -c -f docker-compose.pathfinder-pull.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: pathfinder-proxy
  name: pathfinder-proxy
  namespace: pathfinder
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pathfinder-proxy
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o pathfinder-rpc-server --volumes persistentVolumeClaim -c -f docker-compose.pathfinder-pull.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: pathfinder-proxy
    spec:
      containers:
        - env:
            - name: CORS_ORIGINS
              valueFrom:
                configMapKeyRef:
                  key:  PATHFINDER_PROXY_CORS_ORIGINS
                  name: env
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key:  PATHFINDER_PROXY_PORT
                  name: env
            - name: UPSTREAM_HEALTH_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  key:  PATHFINDER_PROXY_UPSTREAM_HEALTH_ENDPOINTS
                  name: env
            - name: UPSTREAM_SERVICE_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  key:  PATHFINDER_PROXY_UPSTREAM_SERVICE_ENDPOINTS
                  name: env
          image: circlesubi/pathfinder-proxy:latest
          name: pathfinder-proxy
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
