apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --controller statefulset -o pathfinder-rpc-server --volumes persistentVolumeClaim -c
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: pathfinder2
  name: pathfinder2
  namespace: pathfinder
spec:
  clusterIP: None
  ports:
    - name: "54389"
      port: 54389
      targetPort: 54389
  selector:
    io.kompose.service: pathfinder2
  type: ClusterIP
status:
  loadBalancer: {}
