{{- if  .Values.pathfinder.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pathfinder2
  name: pathfinder2
spec:
  clusterIP: None
  ports:
    - name: http
      port: 54389
      targetPort: 54389
    - name: http2
      port: 8794
      targetPort: 8794
  selector:
    app: pathfinder2
  type: ClusterIP
{{- end -}}
