{{- if .Values.pathfinder.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pathfinder2-updater
  name: pathfinder2-updater
spec:
  clusterIP: None
  ports:
    - name: headless
      port: 55555
      targetPort: 0
  selector:
    app: pathfinder2-updater
{{- end -}}
