{{- if  .Values.pathfinder.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pathfinder2-claim
  name: pathfinder2-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
{{- end  -}}
