apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose convert --controller statefulset -o pathfinder-rpc-server --volumes persistentVolumeClaim -c
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: pathfinder2
  name: pathfinder2
  namespace: pathfinder
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pathfinder2
  serviceName: pathfinder2
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: pathfinder2
    spec:
      containers:
        - args:
            - 0.0.0.0:54389
          image: circlesubi/pathfinder2:latest
          name: pathfinder2
          ports:
            - containerPort: 54389
          resources: {}
          volumeMounts:
            - mountPath: /var/pathfinder2/data
              name: pathfinder2-claim0
      restartPolicy: Always
  updateStrategy: {}
  volumeClaimTemplates:
    - metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: pathfinder2-claim0
        name: pathfinder2-claim0
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
      status: {}
status:
  replicas: 0
