{{- if .Values.pathfinder.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: pathfinder2-updater
  name: pathfinder2-updater
  namespace: pathfinder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pathfinder2-updater
  serviceName: pathfinder2-updater
  template:
    metadata:
      labels:
        app: pathfinder2-updater
    spec:
      containers:
        - env:
            - name:     EXTERNAL_CAPACITY_GRAPH_PATH
              valueFrom:
                configMapKeyRef:
                  key:  PATHFINDER_UPDATER_EXTERNAL_CAPACITY_GRAPH_PATH
                  name: env
            - name:     INDEXER_DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  key:  PATHFINDER_UPDATER_INDEXER_DB_CONNECTION_STRING
                  name: pathfinder-updater-connection-string 
            - name:     INDEXER_WS_URL
              valueFrom:
                configMapKeyRef:
                  key:  PATHFINDER_UPDATER_INDEXER_WS_URL
                  name: env
            - name:     INTERNAL_CAPACITY_GRAPH_PATH
              valueFrom:
                configMapKeyRef:
                  key:  PATHFINDER_UPDATER_INTERNAL_CAPACITY_GRAPH_PATH
                  name: env
            - name:     PATHFINDER_RPC_URL
              valueFrom:
                configMapKeyRef:
                  key:  PATHFINDER_UPDATER_RPC_URL
                  name: env
          image: circlesubi/pathfinder2-updater:latest
          name: pathfinder2-updater
          resources: {}
          volumeMounts:
            - mountPath: /var/pathfinder2/data
              name: pathfinder2-claim0
      volumes: 
        - name: pathfinder2-claim0 
          persistentVolumeClaim:
            claimName: pathfinder2-claim0-pathfinder2-0
      restartPolicy: Always
  updateStrategy: {}
{{- end -}}
