{{- if index .Values "pathfinder-proxy" "enabled" -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pathfinder-proxy
  name: pathfinder-proxy
spec:
  ports:
    - name: http
      port: 8675
      targetPort: 8675
  selector:
    app: pathfinder-proxy
{{- end -}}
