{{- if .Values.pathfinder.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: pathfinder2
  name: pathfinder2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pathfinder2
  serviceName: pathfinder2
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pathfinder2
    spec:
      containers:
        - args:
            - 0.0.0.0:54389
          image: circlesubi/pathfinder2:latest
          name: pathfinder2
          ports:
            - containerPort: 54389
          resources: {}
          volumeMounts:
            - mountPath: /var/pathfinder2/data
              name: pathfinder2-claim0
      restartPolicy: Always
  updateStrategy: {}
  volumeClaimTemplates:
    - metadata:
        labels:
          app: pathfinder2
        name: pathfinder2-claim0
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi 
{{- end -}}
