{{- if .Values.pathfinder.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pathfinder2
  name: pathfinder2
spec:
  clusterIP: None
  ports:
    - name: "54389"
      port: 54389
      targetPort: 54389
  selector:
    app: pathfinder2
  type: ClusterIP
{{- end -}}
