apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o pathfinder-rpc-server --volumes persistentVolumeClaim -c -f docker-compose.pathfinder-pull.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: pathfinder2
  name: pathfinder2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pathfinder2
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o pathfinder-rpc-server --volumes persistentVolumeClaim -c -f docker-compose.pathfinder-pull.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: pathfinder2
    spec:
      containers:
        - args:
            - 0.0.0.0:54389
          image: circlesubi/pathfinder2:latest
          name: pathfinder2
          ports:
            - containerPort: 54389
          resources: {}
          volumeMounts:
            - mountPath: /var/pathfinder2/data
              name: pathfinder2-claim0
      restartPolicy: Always
      volumes:
        - name: pathfinder2-claim0
          persistentVolumeClaim:
            claimName: pathfinder2-claim0
status: {}
