---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "..fullname" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configuration | nindent 2 }}
{{- if .Values.tailscale.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tailscale
  labels:
    {{- include "..labels" . | nindent 4 }}
data:
  {{- toYaml .Values.tailscale.configuration | nindent 2 }}
{{- end }}
{{- if .Values.ncat.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ncat
  labels:
    {{- include "..labels" . | nindent 4 }}
data:
  {{- toYaml .Values.ncat.configuration | nindent 2 }}
{{- end }}
