---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "..fullname" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end}}
{{- if .Values.tailscale.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: tailscale
  labels:
    {{- include "..labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.tailscale.secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end}}
{{- end }}
