# LetsEncrypt certificates
acmeEmail:                 
acmeServer:                

# Smart Contracts
contracts:
  hubAddress:


# Default values for pathfinder-rpc-server 


# Blockchain Indexer
blockchainIndexer:
 indexerWebsocketURL:      
 indexerRPCGatewayURL:     
 hubAddress:               
 startFromBlock:           
 
# Pathfinder proxy
pathfinderProxyCorsOrigins: 
pathfinderProxyHost:        

postgresql:
  primary:
    persistence:
      size:                 500Gi


# Pathfinder proxy
pathfinderProxy:
  port: 8675
  upstreamServiceEndpoints: http://pathfinder2:54389
  upstreamHealthEndpoints:  http://pathfinder2-updater:8794

# Pathfinder updater
pathfinderUpdater:
  indexerDBConnectionString:
  indexerWSurl:              ws://blockchain-indexer:8675
  internalCapacityGraph:     /var/pathfinder2/data/capacity_graph.db
  externalCapacityGraph:     /var/pathfinder2/data/capacity_graph.db
  rpcURL:                    http://pathfinder2:54389

postgresql:
  enabled: true
  auth:
    username:                 doadmin
    database:                 index
    existingSecret:           indexer-db-secret 
  primary:
    service:
      type:                   NodePort
      nodePorts:
        postgresql:           "30032"
