# Smart Contracts
contracts:
  hub-address: ""

# Default values for pathfinder-rpc-server 
postgresql:
  enabled: false
  auth:
    username: ""
    database: index
  primary:
    persistence:
      size: 500Gi

# Blockchain Indexer
blockchain-indexer:
  enabled: false
  indexer-websocket-url: ""
  indexer-rpc-gateway-url: ""
  hub-address: ""
  start-from-block: ""

# Pathfinder proxy
pathfinder-proxy:
  enabled: false
  port: "8675"
  cors-origins: ""
  upstream:
    service-endpoints: ""
    health-endpoints: ""

ingress:
  enabled: false
  annotations: {}
  host: ""
  tls:
    enabled: false
    secret: ""
  middlewares:
    cors:
      enabled: false
      name: cors
      origins:
        list: []
        list-regex: []

# Pathfinder
pathfinder:
  enabled: false
  indexer-db-connection-string:
  indexer-ws-url: ws://blockchain-indexer:8675
  internal-capacity-graph: /var/pathfinder2/data/capacity_graph.db
  external-capacity-graph: /var/pathfinder2/data/capacity_graph.db
  rpc-url: http://pathfinder2:54389
