# LetsEncrypt certificates
acmeEmail: circlesubi@gmail.com
acmeServer: https://acme-v02.api.letsencrypt.org/directory

# Smart Contracts
contracts:
  hubAddress:

# Indexer DB
indexerDB:
  db:      index
  user:    doadmin
  pgdata:  var/lib/postgresql/data/pgdata


# Blockchain Indexer
blockchainIndexer:
 indexerConnectionString: "Server=indexer-db;Port=5432;Database=index;User ID=postgres;Password=postgres;Command Timeout=240;"

# Pathfinder proxy
pathfinderProxy:
  port: 80
  upstreamServiceEndpoint: http://pathfinder2:54389
  upstreamHealthEndpoint:  http://pathfinder2-updater:8794

# Pathfinder updater
pathfinderUpdater:
  indexerDBConnectionString:
  indexerWSurl:              ws://blockchain-indexer:8675
  internalCapacityGraph:     /var/pathfinder2/data/capacity_graph.db
  externalCapacityGraph:     /var/pathfinder2/data/capacity_graph.db
  rpcURL:                    http://pathfinder2:54389