# Blockchain Indexer
blockchainIndexer:
 indexerWebsocketURL:     wss://rpc.gnosischain.com/wss
 indexerRPCGatewayURL:    https://rpc.gnosischain.com/
 hubAddress: 

# Pathfinder proxy
pathfinderProxyCorsOrigins: circles.garden
pathfinderProxyHost: pathfinder.circles.garden